name: Publish GNOME Extension

on:
  push:
    tags:
      - '*'  # This will trigger the workflow on every tag push

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install gnome-extension-publisher
        run: |
          python -m pip install --upgrade pip
          pip install gnome-extension-publisher

      - name: build
        run: |
          gep build

      - name: Publish GNOME Extension
        env:
          GEP_USERNAME: ${{ secrets.GEP_USERNAME }}
          GEP_PASSWORD: ${{ secrets.GEP_PASSWORD }}
        run: gep publish
